version: "3.8"

networks:
  depscloud:

services:
  tracker:
    restart: always
    image: depscloud/tracker:${TRACKER_VERSION:-latest}
    hostname: tracker
    networks:
      - depscloud

  extractor:
    restart: always
    image: depscloud/extractor:${EXTRACTOR_VERSION:-latest}
    hostname: extractor
    networks:
      - depscloud

  indexer:
    restart: on-failure
    image: depscloud/indexer:${INDEXER_VERSION:-latest}
    hostname: indexer
    networks:
      - depscloud
    depends_on:
      - extractor
      - tracker
    volumes:
      - ./config.yaml:/etc/indexer/config.yaml
    command:
      - --config=/etc/indexer/config.yaml
      - --workers=1

  gateway:
    restart: always
    image: depscloud/gateway:${GATEWAY_VERSION:-latest}
    hostname: gateway
    networks:
      - depscloud
    depends_on:
      - extractor
      - tracker
    ports:
      - 8080:8080
